### ISSUE TITLE
Remove dependency on rlang remotes?

### ISSUE THREAD

**Issue by isteves** [r-lib/lobstr#17]
I'm having a hard time installing the development version of packages on my Windows machine.  As far as I can tell, the CRAN version of `rlang` is up-to-date enough that removing `rlang` from [`Remotes`](https://github.com/r-lib/lobstr/blob/a80d8f8cb1a4b5f35a2bf1a60d22c3bdbf065602/DESCRIPTION#L31) will fix these installation issues for `lobstr`.

I imagine the changes in `devtools` will eventually fix the errors in the dev version of `rlang` (and by extension `lobstr`) but they currently don't work for Windows.  Not filing the issue in those packages because it seems like the work may already be in progress.

Not entirely sure how to reprex installation issues, but here's what I've got:

```r
> devtools::find_rtools()
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.4)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
> pkgbuild::find_rtools()
[1] TRUE
> devtools::install_github("r-lib/rlang")
Using GitHub PAT from envvar GITHUB_PAT
Downloading GitHub repo r-lib/rlang@master
from URL https://api.github.com/repos/r-lib/rlang/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.4)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing rlang
```

These seem to be related:
https://github.com/r-lib/devtools/issues/1772
https://github.com/r-lib/rlang/pull/510

Let me know if there's something I can do on my end to help with this!

**Comment by hadley** [comment]
Also working on getting lobstr to CRAN in the near future 😄

**Comment by hadley** [comment]
Ooops, I spoke to soon - we need it for `cst()`
