### ISSUE TITLE
Add a plot method

### ISSUE THREAD

**Issue by richierocks** [r-lib/lobstr#34]
Since a lot of the point of this package seems to be to visualize the structure of objects, it would be nice to have a plot method to show the AST/CST as a network (either with ggraph or threejs).

It looks like `ast()` returns a character vector though; so the package might need a data frame representation of the tree first. (Or it could be done from `utils::getParseData()`.)

**Comment by hadley** [comment]
There's no need for an additional data structure, the expression is the data structure. But I think more complicated graphical methods are outside of the scope of this package — I want to stick with console visualisations
