### ISSUE TITLE
modify ast tree

### ISSUE THREAD

**Issue by alperyilmaz** [r-lib/lobstr#43]
Hi, 
My aim is to replace `&` with function `min()` and replace `|` with `max()`. So, ` a & (b | c) ` should be rewritten as `min(a, max(b,c))`. I thought modifying the syntax tree is the way to go. Is it possible to modify `ast()` output and then convert back into an expression?

I'm sharing a small example:
```R
a <- 5
b <- 10
c <- 4
express <- a & (b | c)
express_adv <- (c & b) & (a & (b | c))
```

The rewritten `express` should evaluate to `5` and `express_adv` should evaluate to `4`. Expected expressions are :
```R
min(a, max(b,c))  # modified express 
min( min(c,b), min(a, max(b,c)))  # modified express_adv
```
So, this is before:
```
ast( a & (b | c) )

█─`&` 
├─a 
└─█─`(` 
  └─█─`|` 
    ├─b 
    └─c 
```

and this is after:
```
ast(min(a,(max(b,c))))

█─min 
├─a 
└─█─`(` 
  └─█─max 
    ├─b 
    └─c 
```

**Comment by hadley** [comment]
`ast()` just prints the AST; it already exists in R in a way you can work with. See https://adv-r.hadley.nz/expressions.html#ast-funs for some details.
