### ISSUE TITLE
ast layers display as 'X' on Windows

### ISSUE THREAD

**Issue by tpsteiner** [r-lib/lobstr#7]
'X' makes it hard to read. The blocks on linux/mac looks much better. I think the windows font problem was recently fixed in the skimr package.

Edit: Here is the skimr code to fix windows unicode https://github.com/ropenscilabs/skimr/blob/master/R/utils.R

**Comment by hadley** [comment]
Can you please explain the problem?

**Comment by tpsteiner** [comment]
The node output shape on Windos OS _was_ "X", now it is "o". The block shape character is used on mac and linux OS. It's not much of a problem now though, just inconsistent output between operating systems.

Here's a reprex with the updated "o" shape:


<br/>


    lobstr::ast(25 + 30 * 2)
    #> o-`+` 
    #> +-25 
    #> \-o-`*` 
    #>   +-30 
    #>   \-2

**Comment by hadley** [comment]
That's because windows can't reliably display non-ASCII characters
