### ISSUE TITLE
Differences between lobstr::mem_used() & memuse::Sys.procmem()

### ISSUE THREAD

**Issue by mitch-tanney-coterie** [r-lib/lobstr#73]
I currently see differences in reported memory consumption between the following commands.

```
print(lobstr::mem_used())
print(memuse::Sys.procmem()$size)
```

The result from the `memuse::Sys.procmem()$size` command matches or is very close to the values I see in the RStudio Environment pane.

Therefore, what exactly is `lobstr::mem_used()` describing? I apologize in advance if I'm missing something obvious in [the documentation](https://lobstr.r-lib.org/reference/mem_used.html), but I'm curious to know the differences between these commands.

**Comment by hadley** [comment]
Basically, `mem_used()` reports the memory that R tracks from inside the process, and I suspect what memuse and RStudio track are the memory usage of the entire process (as reported by the operating system).
