### ISSUE TITLE
ast() fails for `=` assignment

### ISSUE THREAD

**Issue by Tazinho** [r-lib/lobstr#8]
`lobstr::ast()` and `pryr::ast()` both return an error, when I want to assign a value via `=`
```
> lobstr::ast(a = 1)
Error in lobstr::ast(a = 1) : unused argument (a = 1)
> pryr::ast(a = 1)
Error in pryr::ast(a = 1) : unused argument (a = 1)
```

In contrast the `<-` assignment is accepted in both
```
> lobstr::ast(a <- 1)
X-`<-` 
+-a 
\-1 
> pryr::ast(a <- 1)
\- ()
  \- `<-
  \- `a
  \-  1 
```

Edit: It is probably because `a = ` implies to look for an argument called a, which can not be found, since `x` is the only argument of `lobstr::ast()` and hence, the best I can come up with is a workaround involving extra brackets

```
> lobstr::ast(x = 1)
1 
> lobstr::ast(a = 1)
Error in lobstr::ast(a = 1) : unused argument (a = 1)
> lobstr::ast(x = a = 1)
Error: unexpected '=' in "lobstr::ast(x = a ="
> lobstr::ast(x = {a = 1})
X-`{` 
\-X-`=` 
  +-a 
  \-1 
> lobstr::ast(x = (a = 1))
X-`(` 
\-X-`=` 
  +-a 
  \-1 
```

**Comment by hadley** [comment]
Another good reason not to use `=` for assignment 😉
